"""SQLAlchemy ORM models for database persistence."""

from datetime import datetime
from sqlalchemy import Column, String, Float, Integer, DateTime, Boolean, Text, Index
from database import Base


class Signal(Base):
    """
    Represents a generated trading signal.
    Tracks all BUY/SELL signals generated by the signal engine.
    """
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(20), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    signal_type = Column(String(10), nullable=False)  # 'BUY', 'SELL', 'HOLD'
    close_price = Column(Float, nullable=False)
    rsi = Column(Float, nullable=True)
    sma_20 = Column(Float, nullable=True)
    sma_50 = Column(Float, nullable=True)
    macd = Column(Float, nullable=True)
    gap_score = Column(Float, nullable=True)
    signal_strength = Column(Float, nullable=True)
    period = Column(String(10), default="1d")  # '1d', '1h', '4h', etc
    interval = Column(String(10), default="1d")
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    __table_args__ = (
        Index('idx_ticker_date', 'ticker', 'date'),
        Index('idx_ticker_signal_type', 'ticker', 'signal_type'),
    )


class Trade(Base):
    """
    Represents an executed trade (entry + exit).
    Tracks position history and P&L.
    """
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(20), nullable=False, index=True)
    entry_date = Column(DateTime, nullable=False)
    exit_date = Column(DateTime, nullable=True)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    position_size = Column(Float, nullable=False)
    entry_signal_id = Column(Integer, nullable=True)  # Reference to Signal table
    exit_signal_id = Column(Integer, nullable=True)
    pnl_amount = Column(Float, nullable=True)  # Exit price - entry price
    pnl_pct = Column(Float, nullable=True)  # (Exit price - entry price) / entry price * 100
    exit_reason = Column(String(50), nullable=True)  # 'SIGNAL', 'STOP_LOSS', 'TAKE_PROFIT', 'OPEN'
    is_closed = Column(Boolean, default=False)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_ticker_entry_date', 'ticker', 'entry_date'),
        Index('idx_is_closed', 'is_closed'),
    )


class PerformanceMetric(Base):
    """
    Aggregated performance statistics per ticker and time period.
    Updated periodically (daily) to track strategy performance.
    """
    __tablename__ = "performance_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(20), nullable=False, index=True)
    metric_date = Column(DateTime, nullable=False)  # The date this metric is for
    period = Column(String(10), default="1d")  # Period used for calculation
    interval = Column(String(10), default="1d")
    
    # Signal statistics
    total_signals = Column(Integer, default=0)
    buy_signals = Column(Integer, default=0)
    sell_signals = Column(Integer, default=0)
    
    # Trade statistics
    total_trades = Column(Integer, default=0)
    closed_trades = Column(Integer, default=0)
    open_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    
    # Performance metrics
    win_rate = Column(Float, nullable=True)  # % of profitable trades
    avg_win_pct = Column(Float, nullable=True)
    avg_loss_pct = Column(Float, nullable=True)
    largest_win_pct = Column(Float, nullable=True)
    largest_loss_pct = Column(Float, nullable=True)
    total_return_pct = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    sharpe_ratio = Column(Float, nullable=True)
    
    # Summary
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_ticker_metric_date', 'ticker', 'metric_date'),
    )
